export const industies = [
    {value:0,label:"农副食品加工业"} ,
    {value:1,label:"食品制造业" },
    {value:2,label:"酒、饮料和精制茶制造业"} ,
    {value:3,label:"烟草制品业"} ,
    {value:4,label:"纺织业" },
    {value:5,label:"纺织服装、服饰业"} ,
    {value:6,label:"皮革、毛皮、羽毛及其制品和制鞋业"} ,
    {value:7,label:"木材加工和木、竹、藤、棕、草制品业"} ,
    {value:8,label:"家具制造业" },
    {value:9,label:"造纸和纸制品业" },
    {value:10,label:"印刷和记录媒介复制业" },
    {value:11,label:"文教、工美、体育和娱乐用品制造业" },
    {value:12,label:"石油、煤炭及其他燃料加工业"} ,
    {value:13,label:"化学原料和化学制品制造业"} ,
    {value:14,label:"医药制造业" },
    {value:15,label:"化学纤维制造业"} ,
    {value:16,label:"橡胶和塑料制品业" },
    {value:17,label:"非金属矿物制品业" },
    {value:18,label:"黑色金属冶炼和压延加工业" },
    {value:19,label:"有色金属冶炼和压延加工业"},
    {value:20,label:"金属制品业" },
    {value:21,label:"通用设备制造业" },
    {value:22,label:"专用设备制造业" },
    {value:23,label:"汽车制造业" },
    {value:24,label:"铁路、船舶、航空航天和其他运输设备制造业"} ,
    {value:25,label:"电气机械和器材制造业"} ,
    {value:26,label:"计算机、通信和其他电子设备制造业" } ,
    {value:27,label:"仪器仪表制造业"} ,
    {value:28,label:"其他制造业" },
    {value:29,label:"废弃资源综合利用业" },
    {value:30,label:"金属制品、机械和设备修理业" }
]